const e=JSON.parse('{"key":"v-7be4f959","path":"/book/15-Exceptions.html","title":"第十五章 异常","lang":"zh-CN","frontmatter":{"description":"[TOC] Java 的基本理念是“结构不佳的代码不能运行”。 改进的错误恢复机制是提高代码健壮性的最强有力的方式。错误恢复在我们所编写的每一个程序中都是基本的要素，但是在 Java 中它显得格外重要，因为 Java 的主要目标之一就是创建供他人使用的程序构件。 发现错误的理想时机是在编译阶段，也就是在你试图运行程序之前。然而，编译期间并不能找出所有的...","head":[["meta",{"property":"og:url","content":"https://xszhu522.github.io/OnJava8/book/15-Exceptions.html"}],["meta",{"property":"og:site_name","content":"On Java 8"}],["meta",{"property":"og:title","content":"第十五章 异常"}],["meta",{"property":"og:description","content":"[TOC] Java 的基本理念是“结构不佳的代码不能运行”。 改进的错误恢复机制是提高代码健壮性的最强有力的方式。错误恢复在我们所编写的每一个程序中都是基本的要素，但是在 Java 中它显得格外重要，因为 Java 的主要目标之一就是创建供他人使用的程序构件。 发现错误的理想时机是在编译阶段，也就是在你试图运行程序之前。然而，编译期间并不能找出所有的..."}],["meta",{"property":"og:type","content":"article"}],["meta",{"property":"og:locale","content":"zh-CN"}],["meta",{"property":"og:updated_time","content":"2020-10-20T03:35:48.000Z"}],["meta",{"property":"article:author","content":"xszhu522"}],["meta",{"property":"article:modified_time","content":"2020-10-20T03:35:48.000Z"}],["script",{"type":"application/ld+json"},"{\\"@context\\":\\"https://schema.org\\",\\"@type\\":\\"Article\\",\\"headline\\":\\"第十五章 异常\\",\\"image\\":[\\"\\"],\\"dateModified\\":\\"2020-10-20T03:35:48.000Z\\",\\"author\\":[{\\"@type\\":\\"Person\\",\\"name\\":\\"xszhu522\\",\\"url\\":\\"https://xszhu522.github.io\\"}]}"]]},"headers":[{"level":2,"title":"异常概念","slug":"异常概念","link":"#异常概念","children":[]},{"level":2,"title":"基本异常","slug":"基本异常","link":"#基本异常","children":[{"level":3,"title":"异常参数","slug":"异常参数","link":"#异常参数","children":[]}]},{"level":2,"title":"异常捕获","slug":"异常捕获","link":"#异常捕获","children":[{"level":3,"title":"try 语句块","slug":"try-语句块","link":"#try-语句块","children":[]},{"level":3,"title":"异常处理程序","slug":"异常处理程序","link":"#异常处理程序","children":[]},{"level":3,"title":"终止与恢复","slug":"终止与恢复","link":"#终止与恢复","children":[]}]},{"level":2,"title":"自定义异常","slug":"自定义异常","link":"#自定义异常","children":[{"level":3,"title":"异常与记录日志","slug":"异常与记录日志","link":"#异常与记录日志","children":[]}]},{"level":2,"title":"异常声明","slug":"异常声明","link":"#异常声明","children":[]},{"level":2,"title":"捕获所有异常","slug":"捕获所有异常","link":"#捕获所有异常","children":[{"level":3,"title":"多重捕获","slug":"多重捕获","link":"#多重捕获","children":[]},{"level":3,"title":"栈轨迹","slug":"栈轨迹","link":"#栈轨迹","children":[]},{"level":3,"title":"重新抛出异常","slug":"重新抛出异常","link":"#重新抛出异常","children":[]},{"level":3,"title":"精准的重新抛出异常","slug":"精准的重新抛出异常","link":"#精准的重新抛出异常","children":[]},{"level":3,"title":"异常链","slug":"异常链","link":"#异常链","children":[]}]},{"level":2,"title":"Java 标准异常","slug":"java-标准异常","link":"#java-标准异常","children":[{"level":3,"title":"特例：RuntimeException","slug":"特例-runtimeexception","link":"#特例-runtimeexception","children":[]}]},{"level":2,"title":"使用 finally 进行清理","slug":"使用-finally-进行清理","link":"#使用-finally-进行清理","children":[{"level":3,"title":"finally 用来做什么？","slug":"finally-用来做什么","link":"#finally-用来做什么","children":[]},{"level":3,"title":"在 return 中使用 finally","slug":"在-return-中使用-finally","link":"#在-return-中使用-finally","children":[]},{"level":3,"title":"缺憾：异常丢失","slug":"缺憾-异常丢失","link":"#缺憾-异常丢失","children":[]}]},{"level":2,"title":"异常限制","slug":"异常限制","link":"#异常限制","children":[]},{"level":2,"title":"构造器","slug":"构造器","link":"#构造器","children":[]},{"level":2,"title":"Try-With-Resources 用法","slug":"try-with-resources-用法","link":"#try-with-resources-用法","children":[{"level":3,"title":"揭示细节","slug":"揭示细节","link":"#揭示细节","children":[]}]},{"level":2,"title":"异常匹配","slug":"异常匹配","link":"#异常匹配","children":[]},{"level":2,"title":"其他可选方式","slug":"其他可选方式","link":"#其他可选方式","children":[{"level":3,"title":"历史","slug":"历史","link":"#历史","children":[]},{"level":3,"title":"观点","slug":"观点","link":"#观点","children":[]},{"level":3,"title":"把异常传递给控制台","slug":"把异常传递给控制台","link":"#把异常传递给控制台","children":[]},{"level":3,"title":"把“被检查的异常”转换为“不检查的异常”","slug":"把-被检查的异常-转换为-不检查的异常","link":"#把-被检查的异常-转换为-不检查的异常","children":[]}]},{"level":2,"title":"异常指南","slug":"异常指南","link":"#异常指南","children":[]},{"level":2,"title":"本章小结","slug":"本章小结","link":"#本章小结","children":[]},{"level":2,"title":"后记：Exception Bizarro World","slug":"后记-exception-bizarro-world","link":"#后记-exception-bizarro-world","children":[]}],"git":{"createdTime":1553949104000,"updatedTime":1603164948000,"contributors":[{"name":"sjsdfg","email":"736777445@qq.com","commits":10},{"name":"xiangflight","email":"xiangflight@foxmail.com","commits":3},{"name":"ChelinTsien","email":"jun54555@gmail.com","commits":2},{"name":"LingCoder","email":"lingcoder@gmail.com","commits":3},{"name":"Hao Lin","email":"1184264181@qq.com","commits":1},{"name":"XuYanxin","email":"funnycodingxu@gmail.com","commits":1},{"name":"legendyql","email":"legendyql@qq.com","commits":1},{"name":"sampert-git","email":"68496372+sampert-git@users.noreply.github.com","commits":1},{"name":"unclesesame","email":"guoxu_1989@163.com","commits":1},{"name":"独奏猫","email":"Solocat@users.noreply.github.com","commits":1}]},"readingTime":{"minutes":80.66,"words":24197},"filePathRelative":"book/15-Exceptions.md","localizedDate":"2019年3月30日","autoDesc":true,"excerpt":""}');export{e as data};
